#!/bin/bash

case "$1" in
    install) docker compose exec node yarn install ;;
    update) docker compose exec node yarn install --immutable ;;
    app) shift; docker compose exec app yarn workspace app run "$@" ;;
    admin) shift; docker compose exec admin yarn workspace admin run "$@" ;;
    yarn) shift; docker compose exec node yarn "$@" ;;
    sh) shift; docker compose exec "$1" sh ;;
    up) docker compose up -d --force-recreate ;;
    down) docker compose down ;;
    restart) docker compose down && docker compose up -d --force-recreate ;;
    logs) shift; docker compose logs -f "$@" ;;
    *) echo "Usage: ./dev {install|app|admin|yarn|sh} [args]" ;;
esac
